
# Default values for thumbor.

replicaCount: 1

env:
  MIXED_STORAGE_DETECTOR_STORAGE: "tc_redis.storages.redis_storage"
  STORAGE: "thumbor.storages.mixed_storage"
  DETECTORS: "['thumbor.detectors.queued_detector.queued_complete_detector']"
  SECURITY_KEY: ""
  AUTO_WEBP: "False"
  USE_GIFSICLE_ENGINE: "False"


service:
  name: thumbor
  type: NodePort
  externalPort: 8000
  internalPort: 8000



