apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: thumbor
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: thumbor
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: dictcp/thumbor
        imagePullPolicy: Always
        args:
          - "thumbor"
        ports:
        - name: http
          containerPort: 8000
        env:
        - name: DETECTORS
          value: "['thumbor.detectors.face_detector','thumbor.detectors.feature_detector']"
        - name: THUMBOR_PORT
          value: "8000"
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8000
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 8000
