apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
      annotations:
{{ toYaml .Values.annotations | indent 8 }}
    spec:
      volumes:
      - name: storage
        {{ if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "fullname" . }}
        {{ else }}
        emptyDir: {}
        {{ end }}
      containers:
      - name: {{ .Chart.Name }}
        image: dictcp/thumbor
        imagePullPolicy: {{ .Values.image.pullPolicy }}

        args:
          - "thumbor"
        ports:
        - name: http
          containerPort: {{ .Values.service.internalPort }}
        env:
        - name: DETECTORS
          value: "['thumbor.detectors.face_detector','thumbor.detectors.feature_detector']"
        - name: ENGINE
          value: "opencv_engine"
        - name: THUMBOR_PORT
          value: {{ .Values.service.internalPort | quote }}
{{- range $name, $value := .Values.env }}
{{- if not (empty $value) }}
        - name: {{ $name | quote }}
          value: {{ $value | quote }}
{{- end }}
{{- end }}
        volumeMounts:
        - name: storage
          mountPath: /app
          readOnly: false
        resources:
{{ toYaml .Values.resources | indent 12 }}
        livenessProbe:
{{ toYaml .Values.livenessProbe | indent 10 }}
        readinessProbe:
{{ toYaml .Values.readinessProbe | indent 10 }}
