apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: thumbor
  annotations:
    kubernetes.io/ingress.global-static-ip-name: thumbor
spec:
  backend:
    serviceName: thumbor
    servicePort: 8000
